### ISSUE TITLE
用RelativeLayout布局，然后Recyclerview上层的控件无法点击

### ISSUE THREAD

**Issue by axkza** [yuqirong/CardSwipeView#5]
求解
&lt;RelativeLayout>
    &nbsp;&nbsp;&nbsp;&nbsp;&lt;Recyclerview>  全屏
    &nbsp;&nbsp;&nbsp;&nbsp;&lt;Button>   右下角
&lt;RelativeLayout>

上面的伪代码，button无法触发onClickLisener

**Comment by yuqirong** [comment]
已经测试 button 可以正常响应 onClickListener ， 没有出现无法触发 onClickLisener 的现象。
![qq 20170527173041](https://cloud.githubusercontent.com/assets/11294375/26520291/15f6b8bc-4302-11e7-954b-7a9a79677bf5.png)
![qq 20170527173056](https://cloud.githubusercontent.com/assets/11294375/26520289/15a62654-4302-11e7-8780-799e8bfc096d.png)
![qq 20170527173127](https://cloud.githubusercontent.com/assets/11294375/26520290/15e21a38-4302-11e7-80ba-935989df4a08.png)

**Comment by axkza** [comment]
发现是我自己弄错了，button点击事件做了一些判断导致的，谢谢
